language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t silentkiller2/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true silentkiller2/docker-react npm run test
